"""add transaction_types table and refactor transactions

Revision ID: 717fe6440139
Revises: cc89e742512a
Create Date: 2026-02-24 17:20:26.159740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '717fe6440139'
down_revision: Union[str, Sequence[str], None] = 'cc89e742512a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) создаём справочник
    op.create_table(
        'transaction_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )

    # 2) сидим типы СРАЗУ
    op.bulk_insert(
        sa.table(
            "transaction_types",
            sa.column("id", sa.Integer),
            sa.column("code", sa.String),
            sa.column("name", sa.String),
        ),
        [
            {"id": 1, "code": "income", "name": "Income"},
            {"id": 2, "code": "expense", "name": "Expense"},
        ],
    )

    # 3) добавляем колонку nullable=True
    op.add_column(
        'transactions',
        sa.Column('transaction_type_id', sa.Integer(), nullable=True)
    )

    # 4) переносим данные из старого type
    op.execute("""
        UPDATE transactions
        SET transaction_type_id = CASE
            WHEN type = 'income' THEN 1
            WHEN type = 'expense' THEN 2
            ELSE NULL
        END
    """)

    # 5) теперь делаем NOT NULL
    op.alter_column('transactions', 'transaction_type_id', nullable=False)

    # 6) создаём FK
    op.create_foreign_key(
        'fk_transactions_transaction_type_id',
        'transactions',
        'transaction_types',
        ['transaction_type_id'],
        ['id']
    )

    # 7) удаляем старую колонку
    op.drop_column('transactions', 'type')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', postgresql.ENUM('income', 'expense', name='transaction_type'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('transactions', 'transaction_type_id')
    op.drop_table('transaction_types')
    # ### end Alembic commands ###
